#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${BACKEND_DIR}"

export AUTH_BYPASS="${AUTH_BYPASS:-true}"
export FIRESTORE_ENABLED="${FIRESTORE_ENABLED:-false}"
export FIRESTORE_PROJECT_ID="${FIRESTORE_PROJECT_ID:-cockatiel-enhanced}"
export PROMPT_VERSION="${PROMPT_VERSION:-v1}"
export AI_ASYNC_ENABLED="${AI_ASYNC_ENABLED:-false}"
export AI_WORKER_ENABLED="${AI_WORKER_ENABLED:-true}"
export AI_WORKER_POLL_INTERVAL_MS="${AI_WORKER_POLL_INTERVAL_MS:-300}"
export AI_WORKER_MAX_RETRIES="${AI_WORKER_MAX_RETRIES:-5}"
export AUDIO_SNIPPET_STORAGE_BACKEND="${AUDIO_SNIPPET_STORAGE_BACKEND:-local}"
export AUDIO_SNIPPET_LOCAL_DIR="${AUDIO_SNIPPET_LOCAL_DIR:-/tmp/vocal-coach/audio-snippets}"
export AUDIO_SNIPPET_RETENTION_DAYS="${AUDIO_SNIPPET_RETENTION_DAYS:-30}"
export AUDIO_SNIPPET_MAX_DURATION_SEC="${AUDIO_SNIPPET_MAX_DURATION_SEC:-10}"
export AUDIO_SNIPPET_MAX_BYTES="${AUDIO_SNIPPET_MAX_BYTES:-2097152}"
export AUDIO_SNIPPET_CLEANUP_BATCH_LIMIT="${AUDIO_SNIPPET_CLEANUP_BATCH_LIMIT:-200}"
export AUDIO_SNIPPET_CLEANUP_WORKER_ENABLED="${AUDIO_SNIPPET_CLEANUP_WORKER_ENABLED:-true}"
export AUDIO_SNIPPET_CLEANUP_INTERVAL_SEC="${AUDIO_SNIPPET_CLEANUP_INTERVAL_SEC:-3600}"

exec uvicorn app.main:app --reload
